### ISSUE TITLE
Добавить комментарии в коде

### ISSUE THREAD

**Issue by Urdzik** [vinnytsiasamungitschool/avt_team_project#1]
Тебе нужно добавит комментарии в коде, чтобы человек который будет работать знал что этот код делает, какая его часть за что отвечает и не было каких-то не понятностей. Напиши кометы что за что отвечает и куда должны посещаться информация которая будет в этом Fragmente.

**Comment by aantonssizov** [comment]
Щас, добавлю, видно не много коментов добавил

**Comment by Urdzik** [comment]
@aantonssizov Код посмотрю завтра, сегодня уже никак)

**Comment by aantonssizov** [comment]
Все коментарии добавил, продолжаю разрабатывать интерфейс :) @Urdzik
